In [3]:
import torch
import numpy as np
import torch.nn.functional as F

import matplotlib.pyplot as plt
%matplotlib inline


In [4]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [5]:
len(words)

32033

In [11]:
# build dictionaries for vocabulary
letters = list(set("".join(words)))
letters = sorted(letters)

# convert string to integers
stoi = {s:i+1 for i, s in enumerate(letters)}
stoi['.'] = 0

# convert integers to string
itos = {i:s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [19]:
# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words[:1]:
    context = [0] * block_size
#     print(context)
    for ch in w + '.':
        ix = stoi[ch]
#         print(ch, "-->", ix)
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix] # crop and append
        
X = torch.tensor(X)
Y = torch.tensor(Y)

... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .


In [21]:
X.shape, Y.shape

(torch.Size([5, 3]), torch.Size([5]))

In [39]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1]])

In [26]:
C = torch.randn((27, 2))

In [27]:
C

tensor([[-0.6065,  0.7123],
        [-0.3051, -0.7095],
        [ 1.3486,  1.3045],
        [ 0.2338, -0.1987],
        [-1.1582, -1.1579],
        [-1.0614, -2.1421],
        [-1.1451,  1.7083],
        [ 0.5922,  1.7476],
        [-0.3254,  1.1892],
        [ 0.9966, -1.7073],
        [ 0.1923, -0.4872],
        [ 0.3349,  0.7023],
        [ 0.7533,  0.4956],
        [ 0.9871,  0.2496],
        [ 0.7430,  0.8056],
        [-1.8598,  0.2690],
        [ 0.3519,  0.3499],
        [-0.0541, -0.2707],
        [ 0.1650,  0.7541],
        [-1.3372, -0.2542],
        [-0.5695,  1.3477],
        [ 0.0484, -1.1394],
        [-0.3579, -1.5169],
        [-0.4982,  1.4325],
        [ 0.2061,  0.8524],
        [ 0.6043, -0.5627],
        [ 0.8335, -0.5254]])

In [37]:
emb = C[X]
emb

tensor([[[-0.6065,  0.7123],
         [-0.6065,  0.7123],
         [-0.6065,  0.7123]],

        [[-0.6065,  0.7123],
         [-0.6065,  0.7123],
         [-1.0614, -2.1421]],

        [[-0.6065,  0.7123],
         [-1.0614, -2.1421],
         [ 0.9871,  0.2496]],

        [[-1.0614, -2.1421],
         [ 0.9871,  0.2496],
         [ 0.9871,  0.2496]],

        [[ 0.9871,  0.2496],
         [ 0.9871,  0.2496],
         [-0.3051, -0.7095]]])

In [38]:
emb.shape

torch.Size([5, 3, 2])